from tkinter import *
from calcFuncs import *

if __name__=="__main__": 
    gui = Tk()
    gui.geometry('300x250')
    gui.title("Scientific Calculator")
    gui.configure(bg="light blue")

    equation = StringVar()
    #output field 
    output = Entry(gui, textvariable=equation)
    output.grid(columnspan=5, ipadx=90)

    buttonClear = Button(gui, text="Clear")
    buttonClear.grid(row=1,column=0)
    buttonCancel = Button(gui, text="Cancel")
    buttonCancel.grid(row=1,column=2)
    buttonEnter = Button(gui, text=" = ", width=4)
    buttonEnter.grid(row=1,column=4)
    #buttons exp,ln,sqrt,sq
    buttonExp = Button(gui,text="exp",height=1,width=4)
    buttonExp.grid(row=2, column=0)
    buttonLN = Button(gui,text="ln",height=1,width=4)
    buttonLN.grid(row=3, column=0)
    buttonSqrt = Button(gui,text="sqrt",height=1,width=4)
    buttonSqrt.grid(row=4, column=0)
    buttonSq = Button(gui,text="sq",height=1,width=4)
    buttonSq.grid(row=5, column=0)
    #buttons 1-9
    button1 = Button(gui, text=" 1 ",height=1,width=4)
    button1.grid(row=2,column=1,pady=5)
    button2 = Button(gui, text=" 2 ",height=1,width=4)
    button2.grid(row=2,column=2)
    button3 = Button(gui, text=" 3 ",height=1,width=4)
    button3.grid(row=2,column=3)
    button4 = Button(gui, text=" 4 ",height=1,width=4)
    button4.grid(row=3,column=1,pady=5)
    button5 = Button(gui, text=" 5 ",height=1,width=4)
    button5.grid(row=3,column=2)
    button6 = Button(gui, text=" 6 ",height=1,width=4)
    button6.grid(row=3,column=3)
    button7 = Button(gui, text=" 7 ",height=1,width=4)
    button7.grid(row=4,column=1)
    button8 = Button(gui, text=" 8 ",height=1,width=4)
    button8.grid(row=4,column=2,pady=5)
    button9 = Button(gui, text=" 9 ",height=1,width=4)
    button9.grid(row=4,column=3)
    button0 = Button(gui, text=" 0 ",height=1,width=4)
    button0.grid(row=5,column=1,pady=5)
    #buttons decimal and +/-
    buttonDec =  Button(gui, text=" . ",height=1,width=4)
    buttonDec.grid(row=5,column=2)
    buttonNeg =  Button(gui, text=" +/- ",height=1,width=4)
    buttonNeg.grid(row=5,column=3)
    #arithmetic buttons 
    buttonAdd = Button(gui,text=" + ", height=1,width=4)
    buttonAdd.grid(row=5,column=4)
    buttonSub = Button(gui,text=" - ", height=1,width=4)
    buttonSub.grid(row=4,column=4)
    buttonMul = Button(gui,text=" * ", height=1,width=4)
    buttonMul.grid(row=3,column=4)
    buttonDiv = Button(gui,text=" / ", height=1,width=4)
    buttonDiv.grid(row=2,column=4)
    #trig buttons 
    buttonSin = Button(gui,text=" sin ", height=1,width=4)
    buttonSin.grid(row=6,column=1,pady=5) 
    buttonCos = Button(gui,text=" cos ", height=1,width=4)
    buttonCos.grid(row=6,column=2)
    buttonTan = Button(gui,text=" tan ", height=1,width=4)
    buttonTan.grid(row=6,column=3)

    gui.mainloop() 